// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmK1zuwPXBspfHUpjrgUwV7uq5fMIojY4',
    appId: '1:191794750052:web:38255614d3bca5942cb571',
    messagingSenderId: '191794750052',
    projectId: 'spotify-tekmob-fea7f',
    authDomain: 'spotify-tekmob-fea7f.firebaseapp.com',
    storageBucket: 'spotify-tekmob-fea7f.appspot.com',
    measurementId: 'G-SZEZ11VTXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLMDgl_ygrvYJYNxNiXYCrZQh2hqKglRs',
    appId: '1:191794750052:android:320bae65c5311ab62cb571',
    messagingSenderId: '191794750052',
    projectId: 'spotify-tekmob-fea7f',
    storageBucket: 'spotify-tekmob-fea7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4vSytP7c5e6_cn34E1nAhQzITEctTQY',
    appId: '1:191794750052:ios:4239b68a8b5fc1852cb571',
    messagingSenderId: '191794750052',
    projectId: 'spotify-tekmob-fea7f',
    storageBucket: 'spotify-tekmob-fea7f.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg4vSytP7c5e6_cn34E1nAhQzITEctTQY',
    appId: '1:191794750052:ios:4239b68a8b5fc1852cb571',
    messagingSenderId: '191794750052',
    projectId: 'spotify-tekmob-fea7f',
    storageBucket: 'spotify-tekmob-fea7f.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmK1zuwPXBspfHUpjrgUwV7uq5fMIojY4',
    appId: '1:191794750052:web:5176e5188edb63892cb571',
    messagingSenderId: '191794750052',
    projectId: 'spotify-tekmob-fea7f',
    authDomain: 'spotify-tekmob-fea7f.firebaseapp.com',
    storageBucket: 'spotify-tekmob-fea7f.appspot.com',
    measurementId: 'G-JLRSESZ1PH',
  );

}